Repository ucsb-cs156-f24/proj-dining-f24-13, pull requests merged in 2024-11, with the labels that each got.

#23 dq-added reviews database table (entity, repository, migration)
  src/main/java/edu/ucsb/cs156/dining/entities/Review.java
  src/main/java/edu/ucsb/cs156/dining/repositories/ReviewRepository.java
  src/main/resources/db/migration/changes/Review.json
Labels: 5, Merge Candidate-CI, Ready-For-Staff

#24 sj-create a placeholder page at the url /myreviews
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/MyReviews/MyReviewsIndexPage.js
  frontend/src/tests/pages/MyReviews/MyReviewsIndexPage.test.js
Labels: 5, Merge Candidate-CI

#25 sj-add placeholder page /moderate
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/Moderate/ModerateIndexPage.js
  frontend/src/tests/pages/Moderate/ModerateIndexPage.test.js
Labels: 5

#28 ez - added reviewFixtures
  frontend/src/fixtures/reviewFixtures.js
Labels: 5, Merge Candidate-CI

#26 sj-create placeholder page for reviews at /reviews/:itemid
  frontend/src/App.js
  frontend/src/main/pages/Reviews/ReviewsLookupPage.js
  frontend/src/tests/pages/Reviews/ReviewsLookupPage.test.js
Labels: 5, Merge Candidate-CI

#29 sj-Create placeholder page for individual dining commons
  frontend/src/App.js
  frontend/src/main/pages/DiningCommons/DiningCommonsPage.js
  frontend/src/tests/pages/DiningCommons/DiningCommonsIndexPage.test.js
Labels: 5

#42 sj-add new columns to users table
  src/main/java/edu/ucsb/cs156/dining/entities/User.java
  src/main/resources/db/migration/changes/Users.json
Labels: 5, Merge Candidate-CI

#40 ez - Created ReviewTable Component + Tests
  frontend/src/main/components/Review/ReviewTable.js
  frontend/src/main/utils/ReviewUtils.js
  frontend/src/stories/components/Review/ReviewTable.stories.js
  frontend/src/tests/components/Review/ReviewTable.test.js
Labels: 10, Merge Candidate-CI

#43 Add DiningCommons service and controller to list dining commons with …
  src/main/java/edu/ucsb/cs156/dining/controllers/DiningCommonsController.java
  src/main/java/edu/ucsb/cs156/dining/models/DiningCommon.java
  src/main/java/edu/ucsb/cs156/dining/services/DiningCommonsService.java
  src/main/resources/application.properties
  src/test/java/edu/ucsb/cs156/dining/controllers/DiningCommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/dining/services/DiningCommonsServiceTest.java
Labels: 10, Merge Candidate-CI

#44 ak-added dining commons fixtures
  frontend/src/fixtures/diningCommonsFixtures.js
Labels: 5, Merge Candidate-CI

#46 dq-ReviewBackend post/get all endpoints + tests
  src/main/java/edu/ucsb/cs156/dining/controllers/ReviewsController.java
  src/main/java/edu/ucsb/cs156/dining/entities/Review.java
  src/test/java/edu/ucsb/cs156/dining/controllers/ReviewsControllerTests.java
Labels: 10

#47 dq-ReviewBackend get by user endpoint + tests
  src/main/java/edu/ucsb/cs156/dining/controllers/ReviewsController.java
  src/test/java/edu/ucsb/cs156/dining/controllers/ReviewsControllerTests.java
Labels: 10, Merge Candidate-CI

#50 Ak diningcommonstable
  frontend/src/fixtures/diningCommonsFixtures.js
  frontend/src/main/components/DiningCommons/DiningCommonsTable.js
  frontend/src/stories/components/DiningCommons/DiningCommonsTable.stories.js
  frontend/src/tests/components/DiningCommons/DiningCommonsTable.test.js
Labels: 10, Merge Candidate-CI

#52 dq-ReviewBackend GET reviews needing moderation, PUT endpoints to update a user's review and moderate a review
  src/main/java/edu/ucsb/cs156/dining/controllers/ReviewsController.java
  src/test/java/edu/ucsb/cs156/dining/controllers/ReviewsControllerTests.java
Labels: 10, Merge Candidate-CI, Ready-For-Staff

#53 Shivani Madhan: Menu Displayed instead of Placeholder — Endpoint for meals
  src/main/java/edu/ucsb/cs156/dining/controllers/DiningMenuAPIController.java
  src/main/java/edu/ucsb/cs156/dining/services/DiningMenuAPIService.java
  src/main/resources/application.properties
  src/test/java/edu/ucsb/cs156/dining/controllers/DiningMenuAPIControllerTests.java
  src/test/java/edu/ucsb/cs156/dining/services/DiningMenuAPIServiceTests.java
Labels: 10, Merge Candidate-CI, Ready-For-Staff

#51 ez - add reviewtable to /myreview page
  frontend/src/main/components/Review/ReviewTable.js
  frontend/src/main/pages/MyReviews/MyReviewsIndexPage.js
  frontend/src/main/utils/ReviewUtils.js
  frontend/src/stories/components/Review/ReviewTable.stories.js
  frontend/src/stories/pages/MyReviews/MyReviewsIndexPage.stories.js
  frontend/src/tests/components/Review/ReviewTable.test.js
  frontend/src/tests/pages/MyReviews/MyReviewsIndexPage.test.js
  src/main/java/edu/ucsb/cs156/dining/controllers/ReviewsController.java
  src/test/java/edu/ucsb/cs156/dining/controllers/ReviewsControllerTests.java
Labels: 10
